name: Extract
 
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  ROM_URL:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Firmware Extractor
         run: |
              git clone --recurse-submodules https://github.com/AndroidDumps/Firmware_extractor.git

       - name: Setup extractor environment
         working-directory: Firmware_extractor
         run: |
              sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename
              sudo apt install liblzma-dev python-pip brotli lz4 aria2c
              pip install backports.lzma protobuf pycrypto twrpdtgen extract-dtb

       - name: Running Firmware Extractor
         working-directory: Firmware_extractor
         run: |
              aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -o "FIRMWARE.tgz" "$ROM_URL"
              ./extractor.sh FIRMWARE.tgz

       - name: Store extracted firmware
         uses: actions/upload-artifact@v2
         with:
         name: Firmware
         path: |
               ./out
